package com.bank.bian.issueddeviceadministration;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Issued Device Administration
 *
 * Business Area:      Operations and Execution
 * Business Domain:    Cards
 * Functional Pattern: Administer
 * Asset Type:         Issued Card
 * Control Record:     Issued Card Administrative Plan
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Issued Device Administration — BIAN Semantic API")
                .description("Service Domain 'Issued Device Administration' (Administer pattern) "
                        + "operating on the 'Issued Card Administrative Plan' control record.")
                .version("0.1.0"));
    }
}
